export const NEWS_LIST_REQUEST = 'NEWS_LIST_REQUEST';
export const NEWS_LIST_SUCCESS = 'NEWS_LIST_SUCCESS';
export const NEWS_LIST_FAIL = 'NEWS_LIST_FAIL';

export const NEWS_DETAILS_REQUEST = 'NEWS_DETAILS_REQUEST';
export const NEWS_DETAILS_SUCCESS = 'NEWS_DETAILS_SUCCESS';
export const NEWS_DETAILS_FAIL = 'NEWS_DETAILS_FAIL';
export const NEWS_DETAILS_RESET = 'NEWS_DETAILS_RESET';

export const CREATE_REVIEW_NEWS_REQUEST = 'CREATE_REVIEW_NEWS_REQUEST';
export const CREATE_REVIEW_NEWS_SUCCESS = 'CREATE_REVIEW_NEWS_SUCCESS';
export const CREATE_REVIEW_NEWS_FAIL = 'CREATE_REVIEW_NEWS_FAIL';
export const CREATE_REVIEW_NEWS_RESET = 'CREATE_REVIEW_NEWS_RESET';

export const DELETE_NEWS_REQUEST = 'DELETE_NEWS_REQUEST';
export const DELETE_NEWS_SUCCESS = 'DELETE_NEWS_SUCCESS';
export const DELETE_NEWS_FAIL = 'DELETE_NEWS_FAIL';

export const DELETE_ALL_NEWS_REQUEST = 'DELETE_ALL_NEWS_REQUEST';
export const DELETE_ALL_NEWS_SUCCESS = 'DELETE_ALL_NEWS_SUCCESS';
export const DELETE_ALL_NEWS_FAIL = 'DELETE_ALL_NEWS_FAIL';

export const CREATE_NEWS_REQUEST = 'CREATE_NEWS_REQUEST';
export const CREATE_NEWS_SUCCESS = 'CREATE_NEWS_SUCCESS';
export const CREATE_NEWS_FAIL = 'CREATE_NEWS_FAIL';
export const CREATE_NEWS_RESET = 'CREATE_NEWS_RESET';

export const UPDATE_NEWS_REQUEST = 'UPDATE_NEWS_REQUEST';
export const UPDATE_NEWS_SUCCESS = 'UPDATE_NEWS_SUCCESS';
export const UPDATE_NEWS_FAIL = 'UPDATE_NEWS_FAIL';
export const UPDATE_NEWS_RESET = 'UPDATE_NEWS_RESET';
